### ISSUE TITLE
依存ライブラリ情報を記述する

### ISSUE THREAD

**Issue by HikaruEgashira** [tomo823/Laf#1]
## 概要

`yt_dlp`のように必要なライブラリ情報がまとまっていると助かります。
tomoさんはpyenv使っていた気がするので、`requirements.txt`に記載する感じでいいかなーと:pray:

## 参考

https://github.com/microsoft/vscode-remote-try-python

**Comment by tomo823** [comment]
承知致しました！

2023年3月29日(水) 22:51 HikaruEgashira ***@***.***>:

**Comment by HikaruEgashira** [comment]
メールじゃなくて https://github.com/tomo823/Laf/issues/1 の方が楽やよ！
ちなみに、

```
pip install -r requirements.txt
```

でインストールできる形式になってない感じする。

**Comment by HikaruEgashira** [comment]
あとこのファイルではできないけど、Pythonのバージョンも指定できるようにしたい。
目標としてはCodespacesでそのまま実行できるようにする。

<img width="683" alt="image" src="https://user-images.githubusercontent.com/39324739/229354318-acc3684e-74f2-4370-8cca-4cba46582707.png">

参考にあげたプロジェクトを参考にするなら、
https://github.com/microsoft/vscode-remote-try-python/blob/main/.devcontainer/devcontainer.json
をコピペしたら6行目に書いてあるバージョンの環境が立ち上がるようになる。

**Comment by HikaruEgashira** [comment]
このあたりの環境は自分がやったほうがいいかもな、tomoくんにコードに集中させる感じで

**Comment by HikaruEgashira** [comment]
ないすです！
