### ISSUE TITLE
書き起こしたtxtファイル

### ISSUE THREAD

**Issue by tomo823** [tomo823/Laf#4]
whisperによって書き起こしたtxtファイルはどこに保存したら良いでしょうか？また、txtファイルのファイル名はそのまま動画のタイトルでよろしいでしょうか？

**Comment by HikaruEgashira** [comment]
## 保存場所

プログラムじゃないので、
https://github.com/tomo823/Laf/releases/new
かGoogle Driveとかが適切ですね。

## ファイル名について

保存形式とか全般は、llamaindexでアクセスしやすい形にするのをおすすめします。
こうすることで、プログラムがシンプルになると思います。

llamaindexでアクセスしやすい形っていうのは、実際に別データでやってみることで学んだ方が理解しやすいと思うので、細かな指定はないです！
